# Generated by Django 3.0.1 on 2020-01-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_main',
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default='http://hehe.com/1.jpg', max_length=300),
            preserve_default=False,
        ),
    ]
