# Generated by Django 3.0.1 on 2020-01-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200105_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.Ad'),
        ),
    ]
