# Generated by Django 3.0.1 on 2020-01-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200108_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='photo',
            name='main_photo',
            field=models.BooleanField(default=False),
        ),
    ]
